locked-blocks:
  method: PASSCODE # PASSCODE or PASSWORD
  keypad:
    enabled: true
    default-tick-delay: 20
  containers:
    chest: true
    shulker-box: true
    barrel: true
    hopper: true
    furnaces: true

modules:
  whitelist: true
  blacklist: true
  harming:
    enabled: true
    damage: 2.0
  disguise:
    enabled: true
    disabled-blocks: []
  more-pins:
    - 3
    - 5
    - 7

codebreaker:
  enabled: true
  success-chance: 0.33

lockpick:
  enabled: true
  default-pins: 1
  break-chance: 0.7

reinforced-blocks:
  enabled: true
  disabled-blocks: []